version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pdf-analyzer-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: pdf_analyzer
      MYSQL_USER: pdfuser
      MYSQL_PASSWORD: pdfpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: